### ISSUE TITLE
ambari-docker image problem

### ISSUE THREAD

**Issue by xiqiangchen** [crashtua/ambari-docker#2]
hi, I got a problem when I run ambari-docker image -r http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.7.0.0/ambari.repo
Are there any more detailed examples for using?
Thank you so much!

------
Traceback (most recent call last):
  File "/usr/local/bin/ambari-docker", line 11, in <module>
    load_entry_point('ambari-docker-utils==0.1', 'console_scripts', 'ambari-docker')()
  File "/usr/local/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 1093, in invoke
    return _process_result(rv)
  File "/usr/local/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 1031, in _process_result
    **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/ambari_docker_utils-0.1-py3.6.egg/ambari_docker/cli/ambari_docker_cli.py", line 217, in process_pipeline
    previous_command_context = pipeline_command.callback(context=previous_command_context, **pipeline_command.args)
  File "/usr/local/lib/python3.6/site-packages/ambari_docker_utils-0.1-py3.6.egg/ambari_docker/cli/ambari_docker_cli.py", line 243, in callback
    agent_image = build_ambari_agent_image(repository, agent_base_image, apply_quirks=apply_quirks)
  File "/usr/local/lib/python3.6/site-packages/ambari_docker_utils-0.1-py3.6.egg/ambari_docker/image_builder.py", line 396, in build_ambari_agent_image
    packages=("ambari-agent",)
  File "/usr/local/lib/python3.6/site-packages/ambari_docker_utils-0.1-py3.6.egg/ambari_docker/image_builder.py", line 295, in _build_ambari_image
    raise Exception("Failed to determine repo file url")
Exception: Failed to determine repo file url

**Comment by crashtua** [comment]
I hope you figured out the issue? Here is a help - https://github.com/crashtua/ambari-docker/wiki/ambari%E2%80%90docker#image - you don't need to specify "ambari.repo" in the end. Thanks.
